version = 1
SPDX-PackageName = "ABAP file formats tools"
SPDX-PackageSupplier = "ABAP file formats team <abap-file-formats@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/SAP/abap-file-formats-tools"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 SAP SE or an SAP affiliate company and ABAP File Formats Tools contributors"
SPDX-License-Identifier = "MIT"
